# the filter currently checks for words that are 3 or more characters.
---
ass: "~~s"
asses: "~~s~s"
asshole: "a~~~~l~"
assholes: "a~~~~~~s"
bastard: b~~~~~d
beastial: b~~~~~~l
beastiality: b~~~~~~l~ty
beastility: b~~st~l~ty
bestial: b~st~~l
bestiality: b~~~~~l~ty
bitch: b~~~h
bitcher: b~~~~r
bitchers: b~~~~rs
bitches: b~~~~~s
bitchin: b~~~~~n
bitching: b~~~~~ng
blowjob: b~~~~~b
blowjobs: b~~~~~~s
bullshit: b~~~~~~t
clit: c~~t
cock: c~~k
cocks: c~~~s
cocksuck: c~~~~~ck
cocksucked: c~~~~~~~~d
cocksucker: c~~~~~~~~r
cocksucking: c~~~~~~~~ng
cocksucks: c~~~~~~~s
cum: c~~
cummer: c~~~~r
cumming: c~~~~~g
cums: c~~s
cumshot: c~~~~~t
cunillingus: c~~~~~~~~~s
cunnilingus: c~~~~~~~~~s
cunt: c~~t
cuntlick: c~~~~~~k
cuntlicker: c~~~~~~~~r
cuntlicking: c~~~~~~~~~g
cunts: c~~~s
cyberfuc: c~~~~~~c
cyberfuck: c~~~~~~~k
cyberfucked: c~~~~~~~~~d
cyberfucker: c~~~~~~~~~r
cyberfuckers: c~~~~~~~~~~s
cyberfucking: cyb~rf~ck~ng
damn: d~mn
dildo: d~ld~
dildos: d~ld~s
dick: d~ck
dink: d~nk
dinks: d~nks
ejaculate: "~j~c~l~t~"
ejaculated: "~j~c~l~t~d"
ejaculates: "~j~c~l~t~s"
ejaculating: "~j~c~l~t~ng"
ejaculatings: "~j~c~l~t~ngs"
ejaculation: "~j~c~l~t~~n"
fag: f~g
fagging: f~~~~~g
faggot: f~~~~t
faggs: f~~~s
fagot: f~~~t
fagots: f~~~~s
fags: f~~s
fart: f~~t
farted: f~~~~d
farting: f~~~~ng
fartings: f~~~~~~s
farts: f~~~s
farty: f~~~y
felatio: f~~~t~~
fellatio: f~~~~t~~
fingerfuck: f~~~~r~~~k
fingerfucked: f~~~~~~~~~~d
fingerfucker: f~~~~~~~~~~r
fingerfuckers: f~~~~rf~~~~rs
fingerfucking: f~~~~rf~~~~ng
fingerfucks: f~~~~~~~~~s
fistfuck: f~~~~~~k
fistfucked: f~~~~ck~d
fistfucker: f~~~~~~~~r
fistfuckers: f~~~~~~~~rs
fistfucking: f~~~~~~~~ng
fistfuckings: f~~~~~~~~ngs
fistfucks: f~~~~~~~s
fuck: ~~~~
fucked: f~~~~d
fucker: f~~~~r
fuckers: f~~~~~s
fuckin: f~~~~n
fucking: f~~~~~g
fuckings: f~~~~~~s
fuckme: f~~~~~
fucks: f~~~~
fuk: f~~
fuckoff: f~~~~~~
fukoff: f~~~~~
fuks: f~~~
gangbang: g~~~~~~g
gangbanged: g~ngb~ng~d
gangbangs: g~ngb~ngs
gaysex: g~~~~x
goddamn: g~dd~mn
hardcoresex: h~~~~~~~~~x
hell: h~ll
horniest: h~rn~~st
horny: h~rny
hotsex: h~ts~x
jism: j~sm
jiz: j~z
jizm: j~zm
kock: k~ck
kondum: k~nd~m
kondums: k~nd~ms
kum: k~m
kumer: k~mm~r
kummer: k~mm~r
kumming: k~mm~ng
kums: k~ms
kunilingus: k~n~l~ng~s
lust: l~st
lusting: l~st~ng
mothafuck: m~~~~~~~k
mothafucka: m~~~~~~~~~
mothafuckas: m~~~~~~~~~s
mothafuckaz: m~~~~~~~~~z
mothafucked: m~~~~~~~~~d
mothafucker: m~~~~~~~~~r
mothafuckers: m~~~~~~~~~rs
mothafuckin: m~~~~~~~~~n
mothafucking: m~~~~~~~~~ng
mothafuckings: m~~~~~~~~~ngs
mothafucks: m~~~~~~~~s
motherfuck: m~~~~~~~~k
motherfucked: m~~~~r~~~~~d
motherfucker: m~~~~r~~~~~r
motherfuckers: m~~~~r~~~~~rs
motherfuckin: m~~~r~~~~~n
motherfucking: m~~~~r~~~~~ng
motherfuckings: m~~~~~~~~~~ngs
motherfucks: m~~~~~~~~~s
niger: n~gg~r
nigger: n~gg~r
niggers: n~gg~rs
orgasim: "~rg~s~m"
orgasims: "~rg~s~ms"
orgasm: "~rg~sm"
orgasms: "~rg~sms"
phonesex: ph~n~s~x
phuk: p~~k
phuked: p~~~~d
phuking: p~~~~ng
phukked: ph~~~~d
phukking: ph~~~~ng
phuks: p~~~s
phuq: ph~q
pis: p~~
piss: p~~~
pisser: p~~~~r
pissed: p~~~~d
pisser: p~~~~r
pissers: p~~~~~s
pises: p~~~~s
pisses: p~~~~s
pisin: p~~~~n
pissin: p~~~~n
pising: p~~~~ng
pissing: p~~~~ng
pisof: p~~~~~f
pissoff: p~~~~~f
porn: p~~~
porno: p~~~~
pornography: p~~~~~~~~~y
pornos: p~~~~s
prick: p~~~~
pricks: p~~~~s
pussies: p~~~~~s
pusies: p~~~~~s
pussy: p~~~y
pusy: p~~~y
pussys: p~~~~s
pusys: p~~~~s
sex: ~~~
sexagenarian: s~~~~~~~~~~n
sexagenarians: s~~~~~~~~~~~s
sexagesimal: s~~~~~~~~~l
sexagesimals: s~~~~~~~~~~s
sexdecillion: s~~~~~~~~~~n
sexdecillions: s~~~~~~~~~~s
sexed: s~~~d
sexes: s~~~s
sexier: s~~~~r
sexiest: s~~~~~t
sexily: s~~~~y
sexiness: s~~~~~~s
sexinesses: s~~~~~~~~s
sexing: s~~~~g
sexism: s~~~~m
sexisms: s~~~~~s
sexist: s~~~t
sexists: s~~~~~s
sexless: s~~~~~s
sexlessly: s~~~~~~~y
sexlessness: s~~~~~~~~~s
sexlessnesses: s~~~~~~~~~~es
sexologies: s~~~~~~~~s
sexologist: s~~~~~~~~t
sexologists: s~~~~~~~~~s
sexology: s~~~~~~y
sexploitation: s~~~~~~~ation
sexploitations: s~~~~~~~ations
sexpot: s~~~~t
sexpots: s~~~~~s
sext: s~~t
sextain: s~~tain
sextains: s~~tains
sextan: s~~tan
sextans: s~~tans
sextant: s~~tant
sextants: s~~tants
sextarii: s~~tarii
sextarius: s~~tarius
sextet: s~~tet
sextets: s~~tets
sextette: s~~tette
sextettes: s~~tettes
sextile: s~~tile
sextiles: s~~tiles
sextillion: s~~tillion
sextillions: s~~tillions
sexto: s~~to
sextodecimo: s~~todecimo
sextodecimos: s~~todecimos
sexton: s~~ton
sextons: s~~tons
sextos: s~~tos
sexts: s~~ts
sextuple: s~~tuple
sextupled: s~~tupled
sextuples: s~~tuples
sextuplet: s~~~~~let
sextuplets: s~~tuplets
sextuplicate: s~~tuplicate
sextuplicated: s~~tuplicated
sextuplicates: s~~tuplicates
sextuplicating: s~~~~~~icating
sextupling: s~~~~~~ing
sextuply: s~~~~~~y
sexual: s~~~~l
sexualities: s~~ualities
sexuality: s~~~~~~ty
sexualization: s~~~~~~zation
sexualizations: s~~~~~~zations
sexualize: s~~~~~~~e
sexualized: s~~~~~~~~d
sexualizes: s~~~~~~~s
sexualizing: s~~~~~~~~~g
sexually: s~~~~~~y
sexy: s~~y
shit: s~~~
shited: s~~~~d
shitfull: s~~~~~~l
shiting: s~~~~~g
shitings: s~~~~~~s
shits: s~~~s
shitted: s~~~~~d
shitter: s~~~~~r
shitters: s~~~~~~s
shitting: s~~~~~~g
shittings: s~~~~~~~s
shitty: s~~~~y
shity: s~~~~y
slut: s~~t
sluts: s~~~s
smut: s~~t
spunk: s~~~k
twat: t~~t
penis: p~~~s
suck: s~~~
sucked: s~~~~~
waste: w~~~~
girl: g~~~
girls: g~~~~
lady: l~~~
ladies: l~~~~
woman: w~~~~
women: w~~~~
bad: b~~
gay: g~~
lesbian: l~~~~~~
worst: w~~~~
